name: Build and push image

on:
  push:
    branches:
      - main

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: rhn-support-ramdr
  IMG_NAME: kuadrant
  IMG_TAGS: unstable
  TARGET_PLATFORM: linux/amd64,linux/s390x  

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: s390x
      - name: Setup buildx
        uses: docker/setup-buildx-action@master
      - name: Log in to Quay
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMG_REGISTRY_HOST }}
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}/${{ env.IMG_NAME }}:${{ env.IMG_TAGS }}
          push: true
          build-args: |
            TARGETARCH=${{ github.event.inputs.targetarch }} 
          platforms: ${{ env.TARGET_PLATFORM }}
          file: |
            ./Dockerfile
