name: Build and push image

on:
  push:
    branches:
      - main

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: rhn-support-ramdr
  IMG_NAME: kuadrant
  IMG_TAGS: unstable
  TARGET_PLATFORM: linux/s390x  

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup buildah 
        uses: redhat-actions/buildah-build@v2
      - name: Build Image
        id: build-image
        run: |
          buildah bud --platform ${{ env.TARGET_PLATFORM }} -t ${{ env.IMG_NAME }} --layers ./Dockerfile
      - name: Push Image
        if: ${{ !env.ACT }}
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
      - name: Print Image URL
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
